# Generated by Django 2.2.17 on 2020-12-09 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='hometown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='mother',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_mother', to=settings.AUTH_USER_MODEL),
        ),
    ]
